### ISSUE TITLE
I'm an idiot.

### ISSUE THREAD

**Issue by MyYoungSav** [435vic/MinecraftMobControl#4]
I'm a bit of an idiot, how do I actually install the plugin? o-o

**Comment by MyYoungSav** [comment]
Okay it was installed, but it no worky for me, maybe it is my server version? I'm on 1.16.4 Paper

**Comment by 435vic** [comment]
Issues are meant for actual bugs, not for asking help. I'm closing this but if you actually want help I can, no problem. But I need a screenshot of the server log, which is all the text that is output when you run the jar on the command line. Otherwise I can't really do much. While I haven't really tested the plugin on 1.16.3 and onward, the changes were so small I didn't think anything would break. Anyway, the server logs would be greatly appreciated. Thank you.

**Comment by windetrsfugwq** [comment]
I need help with installing it on my sever
